layout_spectrum: 0.9014337
color:
  saturation: 1
  brandStrength: 0.5718935
  lightness: 1
  rhythmicContrast: 0.1818188
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.516129
name: Cain
